c = open('c:/Users/user/Documents/GitHub/modutools/index.html', 'r', encoding='utf-8').read()
print('=== index.html ===')
print('class=main-area:', c.count('class="main-area"'))
print('class=main-content:', c.count('class="main-content"'))
print('app-layout (open/close):', c.count('app-layout'))
print('data-theme-toggle:', c.count('data-theme-toggle'))
print('theme-btn:', c.count('theme-btn'))
print('sidebar-logo-wrap:', c.count('sidebar-logo-wrap'))
print()

c2 = open('c:/Users/user/Documents/GitHub/modutools/js/ui-common.js', 'r', encoding='utf-8').read()
print('=== ui-common.js ===')
print('sidebar-logo-wrap:', c2.count('sidebar-logo-wrap'))
print('main-content:', c2.count('main-content'))
print('main-area:', c2.count('main-area'))
print()

c3 = open('c:/Users/user/Documents/GitHub/modutools/css/common.css', 'r', encoding='utf-8').read()
print('=== common.css ===')
print('main-content:', c3.count('main-content'))
print('sidebar-logo-wrap:', c3.count('sidebar-logo-wrap'))
print('theme-btn:', c3.count('theme-btn'))
print('header-bg:', c3.count('header-bg'))
print('sb-active-bg:', c3.count('sb-active-bg'))
print('backdrop-filter:', c3.count('backdrop-filter'))